apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-mysql
  namespace: gitea
spec:
  storageClassName: gitea-mysql-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
