apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-html
  namespace: gitea
spec:
  storageClassName: gitea-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
