apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-gitea.yaml
  - deployment-mysql.yaml
  - ingress-ssh.yaml
  - ingress-web.yaml
  - pv-gitea-data.yaml
  - pv-gitea-mysql.yaml
  - pvc-gitea-data.yaml
  - pvc-gitea-mysql.yaml
  - service-gitea-ssh.yaml
  - service-gitea-web.yaml
  - service-mysql.yaml
images:
  - name: gitea/gitea
    newTag: 1.26.0
    newName: gitea/gitea
  - name: mysql
    newTag: 9.7.0
    newName: mysql
